version: '3'
services:
  sonar:
    container_name: sonarqube
    image: sonarqube
    ports:
     - "9000:9000"
    volumes:
     - sonarconf:/opt/sonarqube/conf
     - sonardata:/opt/sonarqube/data
     - sonarlogs:/opt/sonarqube/logs
     - sonarextensions:/opt/sonarqube/extensions

volumes:
  sonarconf:
  sonardata:
  sonarlogs:
  sonarextensions: